### ISSUE TITLE
Pretty rendering doesn't work

### ISSUE THREAD

**Issue by Hubro** [preactjs/preact-render-to-string#105] opened 2019-07-11 07:39 UTC
```javascript
render(h("div", {foo: 123}, h("div", null, h("p", null, "This is a test!")));

// => '<div foo="123"><div><p>This is a test!</p></div></div>'
```

```javascript
render(h("div", {foo: 123}, h("div", null, h("p", null, "This is a test!"))), {}, {pretty: true});

// => '<div foo="123"><div><p>This is a test!</p></div></div>'
```

Why doesn't `{pretty: true}` have any effect?

Versions:

```
preact 10.0.0-beta.3
preact-render-to-string 5.0.4

**Comment by marvinhagemeister** [comment] 2019-07-11 08:33
Just checked and I can't reproduce that behaviour with the versions you mentioned. Can you share a repo or a codesandbox where we can reproduce the issue?

**Comment by Hubro** [comment] 2019-07-11 08:56
@marvinhagemeister Sure, here you go: https://codesandbox.io/embed/condescending-leakey-zdr5w

Also in terminal:

```
 $ node
> const { h } = require("preact");
undefined
> const { render } = require("preact-render-to-string");
undefined
> render(h("div", {foo: 123}, h("div", null, h("p", null, "This is a test!"))), {}, {pretty: true})
'<div foo="123"><div><p>This is a test!</p></div></div>'
```

**Comment by marvinhagemeister** [comment] 2019-07-11 11:47
Awesome, thanks a bunch for the sandbox 👍 Can confirm that something is wrong there and the code isn't pretty printed.

**Comment by marvinhagemeister** [comment] 2019-07-11 15:24
We've found the cause and merged a fix in `master`. A new release will follow soon :+1:

**Closed** 2019-07-11 15:23 UTC
Labels: bug

**Comment by Hubro** [comment] 2019-07-11 18:34
Nice, thanks!

**Comment by Hubro** [comment] 2019-07-11 18:42
Unfortunately `preact-render-to-string` doesn't seem to work when installed directly from git for some reason:

```
$ yarn add --dev https://github.com/preactjs/preact-render-to-string#master
yarn add v1.16.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.0.7: The platform "linux" is incompatible with this module.
info "fsevents@2.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ preact-render-to-string@5.0.4
info All dependencies
└─ preact-render-to-string@5.0.4
Done in 5.57s.

$ node
> const { render } = require("preact-render-to-string");
Thrown:
{ Error: Cannot find module 'preact-render-to-string'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18) code: 'MODULE_NOT_FOUND' }
```

So I'm eager for that new release... :)

**Comment by marvinhagemeister** [comment] 2019-07-11 21:07
Yup, we don't check in our compiled artifacts as that would produce merge conflicts all the time.

> So I'm eager for that new release... :)

Published as `5.0.5` under the `next` tag. To upgrade just run `npm install preact-render-to-string@next` :100:

**Comment by Hubro** [comment] 2019-07-11 21:45
> Yup, we don't check in our compiled artifacts as that would produce merge conflicts all the time.
> 
> > So I'm eager for that new release... :)
> 
> Published as `5.0.5` under the `next` tag. To upgrade just run `npm install preact-render-to-string@next`

Nice, I'll try it out asap :)

**Comment by Hubro** [comment] 2019-07-12 00:46
Works perfectly now :)

Now I just have to figure out why Jest quotes my strings...

```javascript
exports[`LoginForm renders correctly 1`] = `
"<div id=\\"login-form\\">
	<form>
		<div class=\\"form-group\\">
			<label class=\\"form-label\\" for=\\"username\\">Username</label>
			<input class=\\"form-input\\" type=\\"text\\" name=\\"username\\" id=\\"username\\" />
		</div>
		<div class=\\"form-group\\">
			<label class=\\"form-label\\" for=\\"password\\">Password</label>
			<input class=\\"form-input\\" type=\\"password\\" name=\\"password\\" id=\\"password\\" />
		</div>
		<div class=\\"form-group\\">
			<button class=\\"btn btn-primary\\">Log in</button>
		</div>
	</form>
</div>"
`;
```

Any ideas?

**Comment by marvinhagemeister** [comment] 2019-07-12 06:05
Sweet, glad that it works now :+1: 

I'm unfamiliar with the internals of jest. Best to ask jest devs directly or post an issue on their tracker :slightly_smiling_face:
