### ISSUE TITLE
The output of DOCTYPE is strange.

### ISSUE THREAD

**Issue by shingo-nakanishi** [preactjs/preact-render-to-string#201] opened 2021-09-05 11:15 UTC
Pattern 1:

```
import { html } from 'htm/preact'
import render from "preact-render-to-string"

const r = render(html`<!DOCTYPE html>`)
console.log(r) 
```

Result:
```
!DOCTYPE<undefined></undefined>
```

Pattern 2:
```
import { html } from 'htm/preact'
import render from "preact-render-to-string"

const r = render(html`<!DOCTYPE html />`)
console.log(r)
```

Result:
```
<!DOCTYPE html></!DOCTYPE>
```

I don't think `DOCTYPE` needs the closing tag.
My expected behavior is as follows.

```
const r = render(html`<!DOCTYPE html>`)
console.log(r)
```

Result
```
<!DOCTYPE html>
```

**Comment by marvinhagemeister** [comment] 2021-09-05 12:56
This is the correct and intended behavior. In the readme `htm` is described as:

> `htm` is JSX-like syntax in plain JavaScript - no transpiler necessary.

Therefore it has its roots in JSX which requires a closing tag everywhere without exceptions. With `<!DOCTYPE html>` you're running into another special case of the HTML language. That tag cannot be expressed as a valid JSX element as it doesn't allow the closing `/` and the `!` character is invalid as a tag name in JSX.

I'm assuming that you're attempting to render HTML on the server and what pretty much everyone is doing is to just add the doctype after rendering:

```js
const r = render(html`<h1>my app</h1>`);
// Simply add the doctype in front of the HTML string.
const html = '<!DOCTYPE html>' + r;
```

**Closed by marvinhagemeister** 2021-09-05 12:56 UTC

**Comment by shingo-nakanishi** [comment] 2021-09-05 14:08
Thanks for the reply.
I see, it's a specification.

Your guess is correct.
Many SSG frameworks are overkill, so I'm making my own SSG.

I'll add `'<!DOCTYPE html>'` as a string at the end of the final product as Your code.
