### ISSUE TITLE
Rendering stops on inlined SVG

### ISSUE THREAD

**Issue by kossnocorp** [preactjs/preact-render-to-string#100] opened 2019-06-28 14:39 UTC
`preact-render-to-string` accidentally stops rendering on inlined SVGs, see how it looks:

![Image 2019-06-28 at 6 17 09 PM](https://user-images.githubusercontent.com/52201/60349736-381bb580-99d3-11e9-9e24-0a4231e542f7.png)

`5.0.4` (preact `10.0.0-beta.3`) on the left and `5.0.3` (preact `10.0.0-beta.1`) on the right. 

When the same page is rendered via `preact` on the client, it works fine.

I tested it with few SVGs, and they all behave the same. Here is the SVG from the screenshot: http://i.ncrp.co/8acd64d2a62f

**Comment by marvinhagemeister** [comment] 2019-06-28 15:39
That's strange. Just tried it with the linked SVG, but it renders fine for me. Are you sure that the SVG is causing this? Can you check if there is an error printed in the console?

Let's get to the bottom of this :+1:

**Comment by kossnocorp** [comment] 2019-06-28 16:53
@marvinhagemeister there are no errors in the console. I'm almost certain, but let me frist try to isolate the issue better.

**Comment by kossnocorp** [comment] 2019-06-28 17:22
I'm still getting the problem even though there's nothing but the illustration on the page.

Here's compiled illustration code: https://gist.github.com/kossnocorp/a04c7a488f0f330d1fa13afd1e83ed4c

When I curl the page, it gives up with "(18) transfer closed with 4027 bytes remaining to read"

![Image 2019-06-28 at 9 14 37 PM](https://user-images.githubusercontent.com/52201/60359335-d9ae0180-99e9-11e9-9499-b1236b82a633.png)

However, it works fine on staging: https://staging.diaryemail.com.

I use Node.js 10.16.0, `firebase-tool` to serve the app. The renderer code is also fairly simple: https://gist.github.com/kossnocorp/1b9c7fc25fc3d77921d2841ee224e4ae.

I'm puzzled 🤪

**Comment by developit** [comment] 2019-07-10 18:26
This looks like a `content-length` mismatch. I can't tell from your code sample since its contained in one of the referenced libraries (`#GECK`?), but if it works on staging my guess would be that you're setting the `content-length` response header to a compressed length, but the response is being served uncompressed.

Or, your production hosting is using the compressed length but serving uncompressed bytes.

**Comment by marvinhagemeister** [comment] 2019-07-10 18:32
Yup, some StackOverflow answers also point to that. Locally I cannot reproduce this issue.

**Comment by marvinhagemeister** [comment] 2019-07-12 06:08
Closing because there is a very high chance this is related to a `content-length` mismatch. Please ping us if that doesn't resolve the issue.

**Closed by marvinhagemeister** 2019-07-12 06:08 UTC
